language: ruby
rvm:
  - 2.2.4

addons:
    code_climate:
        repo_token: 19ce549cdec4b3adccf92ed61cffa2e4788b1ae09f24d3867be7f3364064ee47

bundler_args: --without production

script:
  - bundle exec rspec

notifications:
  email: "snepote@gmail.com"