language: ruby
cache: bundler
rvm:
  - 2.2.4

addons:
    code_climate:
        repo_token: baedbbd73bd75d0fea90293d90d6713d843105f057d8cd25f662f0a1f6d09c71

bundler_args: --without production

script:
  - bundle exec rspec

notifications:
  email: "snepote@gmail.com"